### ISSUE TITLE
When either "Acquisition Price Value" or "Valuation AUD" is empty, the record imports into Adlib with text strings

### ISSUE THREAD

**Issue by KirbySLNSW** [ExLibrisGroup/alma-adlib#3] opened 2022-03-06 21:31 UTC
When a record is loaded into the Accessions database without a numerical value in "Acquisition_Price_Value" (VQ)  or "Valuation_AUD" (vA) the record is in Adlib with either "Undefined" or "Nil" in these fields, instead being empty. 
This causes errors when editing the record as the field validation fails due to non-numerical data in numerical fields.

**Comment by mgobat** [comment] 2022-03-14 20:11
@KirbySLNSW, then should these two fields default to 0 (zero) if there is no value?

**Comment by KirbySLNSW** [comment] 2022-03-15 20:40
> 

@mgobat  - It would be our preference to have the fields remain empty (not updated) if there is nothing in the corresponding alma field, however if that is not possible, then 0 will also work.
Many thanks,
Kirby

**Comment by mgobat** [comment] 2022-03-30 13:58
@KirbySLNSW, we just published a new release with a potential fix for this defect. Could you please test and report back? Thanks!

**Comment by KirbySLNSW** [comment] 2022-04-04 01:09
Hi @mgobat ,
Thanks so much for the quick action on this, we appreciate it.
We are not seeing the "null" come through anymore, so that's great.

However, we are seeing an issue now where everything seems to be treated as a Donation and not Donation OR Purchase.
For a purchase, the Price is going in to "Valuation_AUD" (vA) and not "Acquisition_Price_Value" (VQ).  And the Accession date is coming in as the POL creation date, not the date the invoice was paid.  This was working correctly previous to this app update.

Many thanks for the assistance,
Kirby

**Comment by mgobat** [comment] 2022-04-04 12:10
@KirbySLNSW...hmmm...not the expected behavior, especially since I didn't change any code involving dates...or at least not any code I *thought* involved dates. Let me take another look.

**Comment by mgobat** [comment] 2022-04-06 16:11
@KirbySLNSW, the code appears to set the Accession date to the po line creation date, unless there is an invoice. If there is an invoice, the Accession date is either the voucher date (if there is a payment) or the invoice date (if no payment).

The valuation is set to the po line price. If there is an invoice, the valuation is set to null and the price is set to the po line valuation.

Can you confirm if this is the behavior you are seeing?  And if so, what behavior would you prefer?

**Comment by KirbySLNSW** [comment] 2022-05-03 00:08
Hi @mgobat ,
Apologies for the delay in getting back to you - i thought i had submitted a comment  but it doesn't seem to be here!
That is the behaviour we are expecting, however not what we are seeing.
Even if there is an invoice, to price is in the Valuation_AUD field, not the Acquisition_Price_Value field.
Kind regards,
Kirby

**Comment by mgobat** [comment] 2022-05-03 12:18
@KirbySLNSW, thanks for the reply. I'll take another look at the code.

**Comment by mgobat** [comment] 2022-05-03 20:10
@KirbySLNSW, please give the latest version, v1.1.2, a try. Thanks.

**Comment by KirbySLNSW** [comment] 2022-05-04 05:11
Hi @mgobat,
Thank  you so much for your prompt action on this.  Happy to report we have tested and can confirm that it is working as expected now!
Many thanks,
Kirby

**Comment by mgobat** [comment] 2022-05-04 11:47
Excellent news, @KirbySLNSW.  Thank you for the quick confirmation.

**Closed as completed by mgobat** 2022-05-04 11:47 UTC
Labels: bug
